config/routes.rb
Proj4::Application.routes.draw do
  resources :users

  match '/signup', :to => 'users#new'

  match '/sadmin', :to => 'pages#sadmin'

  match '/qadmin', :to => 'pages#qadmin'

  match '/take', :to => 'pages#take'

  match '/results', :to => 'pages#results'
  
  root :to => 'pages#home'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
	attr_accessible :name
	validates :name, :presence => true,
			:length => { :maximum => 50 },
			:uniqueness => true
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessible :name
	
	validates :name, :presence => true,
		:length => { :maximum => 50 },
		:uniqueness => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def sadmin
  	@title = "Survey Administration"
  end

  def qadmin
  	@title = "Question Administration"
  end

  def take
  	@title = "Take Survey"
  end

  def results
  	@title = "View Results"
  end
  
  def signup
  	@title = "Sign up"
  end

end

app/controllers/survey_controller.rb
class SurveyController < ApplicationController
  def show
  	@survey = Survey.find(params[:id])
  	@title = @survey.name
  end
  
  def new
  	@survey = Survey.new
  	@title = "Create Survey"
  end
  
  def create
  	@survey = Survey.new(params[:user])
  	if @survey.save
  		flash[:success] = "Survey successfully created."
  		redirect_to @survey
  	else
  		@title = "Create"
  		render 'new'
  	end
  end
  
  def addq
  	@survey = Survey.find(params[:id])
  	@title = "Add Questions"
  end
  
  def update
  	@survey = Survey.find(params[:id])
  	if @survey.update_attributes(params[:user])
  		flash[:success] = "Survey updated."
  		redirect_to @user
  	else
  		@title = "Add Questions"
  		render 'addq'
  	end
  end

  def index
  	@title = "All Surveys"
  	@surveys = Survey.all
  end
  
  def show
  	@survey = Survey.find(params[:id])
  	@title = @survey.name
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
  	@title = @user.name
  end
  
  def new
  	@user = User.new
  	@title = "Sign up"
  end
  
  def create
  	@user = User.new(params[:user])
  	if @user.save
  		flash[:success] = "Welcome, you are now eligible to take a survey."
  		redirect_to @user
  	else
  		@title = "Sign up"
  		render 'new'
  	end
  end
  
  def edit
  	@user = User.find(params[:id])
  	@title = "Edit user"
  end
  
  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(params[:user])
  		flash[:success] = "Profile updated."
  		redirect_to @user
  	else
  		@title = "Edit user"
  		render 'edit'
  	end
  end

  def index
  	@title = "All users"
  	@users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = "CS 441 - Project 4 - Survey Engine"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "View Results", results_path %></li>
      <li><%= link_to "Survey Admin", sadmin_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("logo.png", :alt => "Sample App", :class => "round") %>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Survey Admin", sadmin_path %></li>
      <li><%= link_to "Q Admin", qadmin_path %></li>
      <li><%= link_to "Take Survey", take_path %></li>
      <li><%= link_to "View Results", results_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>

    <section class="round">
    	<%= flash.each do |key, value| %>
    		<div class="flash <%= key %>"><%= value %></div>
    	<% end %>
    	<% yield %>
    </section>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
              <% flash.each do |key, value| %>
          		<div class="flash <%= key %>"><%= value %></div>
        	<% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>
	List serveys here
</p>
<%= link_to "Take Survey", take_path, :class => "signup_button round" %><P></P>
<%= link_to "Survey Administration", sadmin_path, :class => "signup_button round" %><P></P>
<%= link_to "View Results", results_path, :class => "signup_button round" %><P></P>

app/views/pages/qadmin.html.erb
<h1>Question Administration</h1>
<p>
      Create a Question
      Modify a Question
      Delete a Question
</p>

app/views/pages/results.html.erb
<h1>Survey Results</h1>
<p>
      Display questions and answers to a survey
</p>

app/views/pages/sadmin.html.erb
<h1>Survey Administration</h1>
<p>
      Create Survey<P></P>
      Add Questions<P></P>
      Delete Survey<P></P>
</p>

app/views/pages/take.html.erb
<h1>Take this survey</h1>
<p>
      Sign up to take a survey
      <li><%= link_to "Sign up", signup_path %></li>
</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/survey/new.html.erb
<h1>Survey#new</h1>
<p>Find me in app/views/survey/new.html.erb</p>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

<ul class="users">
      <%= render @users %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for (@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>